# Generated by Django 5.0.10 on 2025-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_newsandevents_summary_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('Yangilik', 'Yangilik'), ('Voqea', 'Voqea')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Birinchi', 'Birinchi'), ('Ikkikchi', 'Ikkinchi'), ('Uchinchi', 'Uchinchi')], max_length=10),
        ),
    ]
