# Generated by Django 4.0.8 on 2024-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary_uz',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='summary_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='summary_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
