# Generated by Django 4.0.8 on 2024-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_choice_choice_text_uz_question_content_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_es',
            new_name='choice_text_kk',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_fr',
            new_name='choice_text_ko',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content_es',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content_fr',
            new_name='content_ko',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_es',
            new_name='explanation_kk',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_fr',
            new_name='explanation_ko',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description_es',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description_fr',
            new_name='description_ko',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title_es',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title_fr',
            new_name='title_ko',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text_tr',
            field=models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_tr',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_tr',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_tr',
            field=models.TextField(blank=True, help_text='A detailed description of the quiz', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_tr',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
