# Generated by Django 4.0.8 on 2024-12-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_choice_text_es_choice_choice_text_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_kk',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ko',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_tr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_kk',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ko',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_kk',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ko',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_tr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ko',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ko',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_tr',
        ),
    ]
