# Generated by Django 5.0.10 on 2025-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.TextField(blank=True, choices=[('Ota', 'Ota'), ('Ona', 'Ona'), ('Aka', 'Aka'), ('Singil', 'Singil'), ('Katta opa', 'Katta opa'), ('Katta aka', 'Katta aka'), ('Boshqa', 'Boshqa')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Kundizgi', 'Kundizgi '), ('Kechki', 'Kechki ')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, null=True),
        ),
    ]
